### ISSUE TITLE
Uso de sprites en TpFinal

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#10]
Debemos agregar e implentar los sprites, ya en frutas y main character para poder avanzar con el proyecto.
Luego revisar que estos esten totalmente funcionales.

**Comment by AnaCatalina** [comment]
Primero agregaré las carpetas con los sprites dentro de la carpeta del proyecto. De esta manera nos permitirá usarlos posteriormente en el programa

**Comment by AnaCatalina** [comment]
Implementé los sprites y también les otorgué movimiento

**Comment by AnaCatalina** [comment]
Ahora haré que se visualicen en el juego para corroborar que todo esté en orden y les mandaré los cambios
