### ISSUE TITLE
Modificación en clases hijas

### ISSUE THREAD

**Issue by AnaCatalina** [estradalautaro/TrabajoFinalGrupo12#11]
Las clases Fruta y FrutaPodrida tienen un atributo de tipo float llamada velocidad, que ya está declarado y heredado desde el GameObject. A su vez, las clases Fruta, FrutaPodrida y Jugador ya heredan también los métodos accesores de la superclase GameObject. Por lo tanto necesitan correcciones.

**Comment by estradalautaro** [comment]
Esta listo
