### ISSUE TITLE
Documentacion de Frutas y FrutaPodrida

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#13]
Se necesita documentar la misma para tener una idea para la implementacion de Colisiones

**Comment by AnaCatalina** [comment]
Ahora empezaré con la documentación

**Comment by AnaCatalina** [comment]
Finalicé la tarea. Pero también aproveché para optimizar parte del código con respecto a la variable posicion en cada constructor
