### ISSUE TITLE
Empiezan las Colisiones

### ISSUE THREAD

**Issue by AnaCatalina** [estradalautaro/TrabajoFinalGrupo12#14]
Se necesita comprobar si las frutas (tanto normales como podridas) colisionan con el jugador.

**Comment by estradalautaro** [comment]
Mostre unos avanzes, luego lo modificare para que este mas optimizado

**Comment by estradalautaro** [comment]
Se completo la colision mejorada, ahora se llegara a instanciar los puntajes para las frutas
