### ISSUE TITLE
ArrayList para Frutas/Fruta Podrida

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#17]
Se necesita que se cree un ArrayList para Fruta y Fruta podrida, para la creacion de varios objetos de esas clases

**Comment by AnaCatalina** [comment]
Enviaré mi progreso en una nueva rama pero aún no termino, lo terminaré mañana

**Comment by estradalautaro** [comment]
También cree una rama adicional con mis pruebas, luego comprobamos ambas y la terminamos antes del envió de hoy

**Comment by AnaCatalina** [comment]
Ya finalicé la tarea
