### ISSUE TITLE
Arreglos en Sprites, añadir musica y fondo para los niveles

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#18]
Se requiere lo siguiente:
-Haga recorte los sprites para movimiento ya que al intentar implementarlos estos dan un error, eliminar el fondo verde y volver a agregarlos a la carpeta de sprites, importante no eliminar maincharacter y escenario, solo reemplazar las otras imagenes con las ya corregidas para su nueva prueba
-Agregar musica acorde al juego, esta debe ir en la carpeta del archivo mas no implementarla todavia

**Comment by JaelMSpinosa** [comment]
Acabo de modificar los sprites y añadi los fondos. Me falta la música y las animaciones.

**Comment by JaelMSpinosa** [comment]
Acabo de agregar 4 pistas de audio para los niveles y el estado inicial del juego. Solo me faltan los sprites.

**Comment by JaelMSpinosa** [comment]
Bien chicos cambie los fondos sacandole los marcos negros y agregue dos animaciones. Me faltan 3. pero ya estan los sprites sin fondo.

**Comment by estradalautaro** [comment]
Apenas termines de agregar los 3 sprites faltantes cerra la tarea, revisa que tenes otra tarea mas en el campo

**Comment by JaelMSpinosa** [comment]
Termine de subir las animaciones y otras cosas que faltaban. Mas los sonidos y musica.
