### ISSUE TITLE
Clase MaquinaEstados

### ISSUE THREAD

**Issue by AnaCatalina** [estradalautaro/TrabajoFinalGrupo12#21]
Se necesita crear la clase MaquinaEstados, la cual se obtendrán las constantes para las etapas del juego (pantalla de inicio, niveles, pantalla de win y pantalla de game over).

**Comment by estradalautaro** [comment]
Se creo la MaquinaEstado para las distintas etapas del juego(añadidas para Instruccionando,Nivel1,Nivel2,Nivel3,Pantalla de Ganar una partida y otra para Perder)
