### ISSUE TITLE
 Actualizar Sketch

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#25]
Se necesita mover declaracioens de objetos, instanciaciones y llamados de métodos del sketch a la clase Regla.

**Comment by AnaCatalina** [comment]
Bien, ahora lo paso

**Comment by AnaCatalina** [comment]
Al realizar el pasaje, el sistema de puntos se vió afectado, puesto que tendremos que solucionarlo.
Además que creé el objeto regla de la clase Regla y tuve que instanciarlo y llamarlo para que cumpla con su función
