### ISSUE TITLE
Mejorar y Actualizar Colisión

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#26]
Se necesita arreglar el método colisión de las Frutas y FrutasPodridas, para que no traspasen el escenario(imagen) hacia el lienzo(marco).

**Comment by AnaCatalina** [comment]
Ahora lo hago

**Comment by AnaCatalina** [comment]
Realicé los siguientes cambios:
-Clase Fruta: Limité la posición desde la que se crearán para que solo se vean en escenario, creé el método colisionarEscenarioF para detectar si la fruta colisiona con el borde del lienzo.
-Clase Fruta Podrida: Limité la posición desde la que se crearán para que solo se vean en escenario, creé el método colisionarEscenarioF para detectar si la fruta colisiona con el borde del lienzo y por último eliminé los métodos accesores de esta clase.
-Clase Jugador: En el método mover añadí un constrain que otorga límites a los objetos en movimiento, para que el jugador se mueva dentro de los límites establecidos por el escenario.
-Clase Regla: Modifiqué los 2 for que recorren las listas de Fruta y Fruta Podrida para detectar si colisionan con el jugador y removerse. Además añadí 2 for más que también recorren las listas de Fruta y Fruta Podrida para detectar si colisionan con el borde inferior de escenario y removerse.
-Y por último eliminé de todas las clases el arrayList <Regla>regla ya que no se lo utiliza.
