### ISSUE TITLE
Bajar peso de imagenes

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#27]
Necesitamos que bajes el peso de todas las imagenes(fondos especialmente), faltan los fondos correspondientes a victoria y derrota del jugador

**Comment by AnaCatalina** [comment]
Ya les bajé el peso y ahora guardo los cambios

**Comment by estradalautaro** [comment]
Gracias. eran demasiado pesada cada imagen, la musica quedo bien

**Comment by AnaCatalina** [comment]
Ya está todo, por ende cerraré esta tarea
