### ISSUE TITLE
Modelado Actualizado

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#35]
Se requiere realizar un nuevo modelado actualizado con los cambios hechos en processing

**Comment by JaelMSpinosa** [comment]
Perfecto.

**Comment by BanegasIvan** [comment]
El modelado fue corregido con los últimos detalles del Proccesing

**Comment by BanegasIvan** [comment]
![trabajofinalfpoo Class diagram](https://user-images.githubusercontent.com/93291192/141662634-8c5b839e-b18a-4647-8398-9076626b41ec.png)
