### ISSUE TITLE
Asignar la tarea de arreglar la herencia de las clases nombradas

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#7]
Las clases hijas "Fruta, FrutaPodrida y Jugador" heredarán de "FrameObject". A su vez "FrameObject" heredará de la superclase "GameObject"

**Comment by AnaCatalina** [comment]
Ahora lo realizo

**Comment by AnaCatalina** [comment]
Terminé
