### ISSUE TITLE
Correcciones en el diagrama de clases

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#8]
Se le asigna ir haciendo algunas correcciones en el diagrama de clases acorde a los cambios realizados

**Comment by BanegasIvan** [comment]
Se completó la corrección en el diagrama de clase agregándose la clase FrameObject

**Comment by estradalautaro** [comment]
Muy bien, cuando termines envia el comentario con el boton "Close with comment" Luego manda el archvo del modelado que lo encesitamos

**Comment by AnaCatalina** [comment]
Ya pasó el Modelado final en otra Issue #9 Modelado de la clase, por ende cierro esta Issue
