### ISSUE TITLE
Modelado de la clase

### ISSUE THREAD

**Issue by estradalautaro** [estradalautaro/TrabajoFinalGrupo12#9]
Esta tarea debe ser realizada luego de corroborar que todo este en orden antes de la entrega del Sabado

**Comment by BanegasIvan** [comment]
Aquí subo el modelio actualizado con los cambios realizados en proccesing hasta la fecha
![trabajofinalfpoo Class diagram](https://user-images.githubusercontent.com/93291192/140629434-2814d98c-19a3-4265-90d6-7cbf669ab3e4.png)
